# Generated by Django 2.0.4 on 2018-04-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hrs_cnt',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
