# Generated by Django 2.0.4 on 2018-04-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_person_hrs_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hands_cnt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='hrs_cnt',
            field=models.IntegerField(),
        ),
    ]
